name: osteriamadonna
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  accordion: ^2.5.1
  cloud_firestore: ^4.8.2
  cupertino_icons: ^1.0.0
  
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
    
    
